name: Weather Data Automation

on:
  schedule:
    - cron: '0 11 * * *' # Every day at 10 AM
  workflow_dispatch:

jobs:
  weather_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run weather script
      run: ./weather.sh

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Owen Coughlan"
        git config --global user.email "g00439345@atu.ie"
        git add weather_data/
        git commit -m "Add new weather data $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin main

