name: Weather Data Automation

on:
  schedule:
    - cron: '0 12 * * *' # Every day at 10 AM
  workflow_dispatch:

jobs:
  weather_job:
    runs-on: ubuntu-latest

    steps:
    - name: computer_infrastructure_assessment
      uses: actions/checkout@v3

    - name: Run weather script
      run: ./weather.sh

    - name: Commit and push changes
      run: |


