name: Weather Data Automation

on:
  schedule:
    - cron: '0 10 * * *' # Every day at 10 AM
  workflow_dispatch:

jobs:
  weather_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run weather script
      run: ./weather.sh

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data/weather
        git commit -m "Automated weather data update"
        git push
