name: Weather Data Automation

on:
  schedule:
    - cron: '0 10 * * *' # Every day at 10 AM
  workflow_dispatch:

jobs:
  weather_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run weather script
      run: ./weather.sh

    - name: Commit and push changes
      run: |

git add data/weather/20241212_101844_weather.json
git commit -m "Add weather data for 2024-12-12"
git push origin <computer_infrastructure_assessment>
